platform :ios, '13.0'
use_frameworks!

target 'OctagonAnalyticsService_Example' do
  pod 'OctagonAnalyticsService', :path => '../'

  target 'OctagonAnalyticsService_Tests' do
    inherit! :search_paths

    
  end
end
